### ISSUE TITLE
Error when i am trying to run this project on NS-3.35

### ISSUE THREAD

**Issue by ajaiknmecap** [TanzimAzadNishan/NS3-Priority-Based-Congestion-Control-Protocol#1]
Dear Sir,
I am facing the issue which is  given below . Please help me.

../src/traffic-control/model/traffic-control-layer.cc: In member function ‘virtual void ns3::TrafficControlLayer::Send(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::QueueDiscItem>)’:
../src/traffic-control/model/traffic-control-layer.cc:424:14: error: ‘class ns3::NetDevice’ has no member named ‘ipAddr’
   if(device->ipAddr == option->GetParentAddress()){
              ^~~~~~
../src/traffic-control/model/traffic-control-layer.cc:448:81: error: ‘class ns3::NetDevice’ has no member named ‘ipAddr’
     std::cout<<"node="<<m_node->GetId()<< ": Not Upstream traffic: " << device->ipAddr << ", " << option->GetParentAddress() << "\n";

**Comment by TanzimAzadNishan** [comment]
You have to replace the build/ns3/net-device.h file with the following file
https://github.com/TanzimAzadNishan/NS3-Priority-Based-Congestion-Control-Protocol/blob/main/pccp/net-device.h
The above file contains the member ipAddr (line no 365)

Sorry for the late reply. I was busy with my academic schedules.

**Comment by TanzimAzadNishan** [comment]
build/ns3/net-device.h file has no write permission by default. You have to make it writable by the chmod command.

**Comment by ajaiknmecap** [comment]
Hi, I have done all things accordingly but again i m getting the error
../src/traffic-control/model/traffic-control-layer.cc: In member function ‘virtual void ns3::TrafficControlLayer::Send(ns3::Ptr<ns3::NetDevice>, ns3::Ptr<ns3::QueueDiscItem>)’:
../src/traffic-control/model/traffic-control-layer.cc:424:14: error: ‘class ns3::NetDevice’ has no member named ‘ipAddr’
   if(device->ipAddr == option->GetParentAddress()){
              ^~~~~~
../src/traffic-control/model/traffic-control-layer.cc:448:81: error: ‘class ns3::NetDevice’ has no member named ‘ipAddr’
     std::cout<<"node="<<m_node->GetId()<< ": Not Upstream traffic: " << device->ipAddr << ", " << option->GetParentAddress() << "\n";
                                                                                 ^~~~~~

**Comment by ajaiknmecap** [comment]
Hi Sir,
its working when i am running by using this command : ./waf --run scratch/pccpTest 

but when i am running by using this command: ./waf --run "scratch/pccpTest --nFlows=20" --cwd="Output/pccpTest"
I am getting the error given below.



gsr@gsr-ThinkCentre-M93p:~/ns-allinone-3.35/ns-3.35$ ./waf --run "scratch/pccpTest --nFlows=20" --cwd="Output/pccpTest"
Waf: Entering directory `/home/gsr/ns-allinone-3.35/ns-3.35/build'
Waf: Leaving directory `/home/gsr/ns-allinone-3.35/ns-3.35/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (1.072s)
Traceback (most recent call last):
  File "/home/gsr/ns-allinone-3.35/ns-3.35/wutils.py", line 144, in run_argv
    WindowsError
NameError: name 'WindowsError' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gsr/ns-allinone-3.35/ns-3.35/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/gsr/ns-allinone-3.35/ns-3.35/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 184, in run_commands
    run_command('shutdown')
  File "/home/gsr/ns-allinone-3.35/ns-3.35/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Scripting.py", line 173, in run_command
    ctx.execute()
  File "/home/gsr/ns-allinone-3.35/ns-3.35/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/gsr/ns-allinone-3.35/ns-3.35/.waf3-2.0.21-c6c9a875365426e5928462b9b74d40b5/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/gsr/ns-allinone-3.35/ns-3.35/wscript", line 1428, in shutdown
    visualize=Options.options.visualize)
  File "/home/gsr/ns-allinone-3.35/ns-3.35/wutils.py", line 238, in run_program
    return run_argv(execvec, env, cwd=cwd)
  File "/home/gsr/ns-allinone-3.35/ns-3.35/wutils.py", line 146, in run_argv
    retval = subprocess.Popen(argv, env=proc_env, cwd=cwd).wait()
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Output/pccpTest': 'Output/pccpTest'

**Comment by TanzimAzadNishan** [comment]
I am not sure about why you are getting the 'WindowsError'. In a linux native environment, this error shouldn't be occurred. I have used ubuntu for this project. Are you running the project in VM or WSL?
